### ISSUE TITLE
Providing UGent Permanence news

### ISSUE THREAD

**Issue by TomNaessens** [ZeusWPI/hydra#110]
Regadering the following email:

> Hier op het PermanentieCentrum gebruiken wij Twitter om belangrijke info te verspreiden.
> Wij gebruiken die bij onverwachtse gebeurtenissen zoals grote stroomonderbrekingen,
> problemen met toevoer van water, telefonie,…
> Alles wat je kan bedenken, dat relevant is voor een groep gebruikers komt op onze Twitter
> te staan.
> 
> Nu hadden wij graag geweten of het mogelijk is om onze Twitter-feed een plaatsje te geven
> in jullie app?  Zo kunnen wij nog meer mensen bereiken en nog vlugger belangrijke
> informatie verspreiden.

What would be the best place to offer this information and when (milestone) would we integrate it?

**Comment by niknetniko** [comment]
There are no plans to integrate this at the moment, and there haven't been plans for some time.
