### ISSUE TITLE
Add support for JSONP

### ISSUE THREAD

**Issue by tivervac** [ZeusWPI/hydra#186]

**Comment by Zepheus** [comment]
An alternative to this is adding CORS headers on the nginx backend for the specific json files. This way, 3rd party sites can use the data as well within a web-app.

More information: 
https://michielkalkman.com/snippets/nginx-cors-open-configuration.html

**Comment by niknetniko** [comment]
CORS has been added to ansible and will be live in the future.

**Comment by redfast00** [comment]
@niknetniko ~in the future~ right now!
