### ISSUE TITLE
Add Minerva-stream

### ISSUE THREAD

**Issue by maartenhbe** [ZeusWPI/hydra#196]
On Minerva each student can find an RSS-link to get an automatic update of all news items published in any of his or her courses. I think it would be nice if one could login via CAS in the Hydra app and get automatic push messages by the app on one's smartphone about Minerva posts (especially posts that are not e-mailed). This way the app integrates not only with leisure activities but also with the educational part of being a student.

Retrieving the link of the feed can be done if we can fetch the required user id and key via CAS or by parsing the HTML (link has a fixed format so a regex should do the trick).

A user might install a seperate RSS-reader off course but most students don't even know what an RSS-feed is. 

This feature can imho increase the overall usefulness of the app.

**Comment by feliciaan** [comment]
We're asking DICT for a minerva API :)
