### ISSUE TITLE
Limit the news articles to a relevant period

### ISSUE THREAD

**Issue by nielsdg** [ZeusWPI/hydra#212]
Right now, in the news section, there are articles which go back to an FK event promotion in February 2012.  These aren't relevant and should be hidden imo.

**Comment by feliciaan** [comment]
All articles are old :( , maybe it's better to fix it at the API-level, because we do not know how long an article is relevant.

**Comment by nielsdg** [comment]
Maybe add an extra source as well? Tbh, I don't see why we shouldn't add the GSR news or even the VVS news.

In any case, we could also let the user give a preference how far back in time their news article list should go (with a default of this and the previous academic year). Very important articles can be pinned then at the API-level?

**Comment by feliciaan** [comment]
The GSR can currently post news through the DSA info panel, on student.UGent.be, maybe we should let them know that. I do not object adding them, but maybe they could use the existing API?

**Comment by nielsdg** [comment]
Dunno. I think it would be better if they could use their own feed, otherwise it would be confusing as it would look like student@gent is the author of a GSR-article.

**Comment by feliciaan** [comment]
It would be clear who the author would be, default author is the association of the person who creates the news article, so this could also be someone from the GSR. Is their already a feed from the GSR available?

**Comment by feliciaan** [comment]
@mlumingu I think you can give a better answer here than me :)

**Comment by mlumingu** [comment]
Yes, as feliciaan says, all student clubs or organisations that have access to our control panel(including gsr) have access to the feed. For each post, there is an attribute indicating which club made that post.

@feliciaan You were talking about a fix for the problem of old articles at the api level. Maybe an extra attribute indicating when the article should no longer be included in the feed?

**Comment by nielsdg** [comment]
But as it is right now, the DSA and other associations use it too little. To the common student, the news section has become irrelevant.

Another solution would be that every FB-post of the DSA is automatically (or manually) posted to  the DSA-site?

**Comment by feliciaan** [comment]
@myncke fix plz

**Comment by sibebleuze** [comment]
I think it would be a good idea to apply this 'relevant period' thing to the announcements too. They also go back a couple of years.

**Comment by niknetniko** [comment]
In the [DSA API v3](http://student.ugent.be/hydra/api/3.0/), the news has been replaced by the official news from Ghent University, so I don't think this is relevant anymore.
