### ISSUE TITLE
Resto Menu visual bugs

### ISSUE THREAD

**Issue by nielsdg** [ZeusWPI/hydra#213]
* The menu category and contents overlap when scrolling ![image](https://cloud.githubusercontent.com/assets/1382976/10454638/7552acea-71b6-11e5-8261-974bcc570fc7.jpg)
* Imo, the top bar is a bit big (taking away a lot of place from the content)
* Can't scroll to legend contents in info tab

**Comment by feliciaan** [comment]
Should be fixed.
