### ISSUE TITLE
iPad version

### ISSUE THREAD

**Issue by nielsdg** [ZeusWPI/hydra#214]
Right now, an iPad user has to choose between either using a small part of the screen or getting this enormously stretched out version.
![image](https://cloud.githubusercontent.com/assets/1382976/10454713/0cb92f14-71b7-11e5-9905-785798677d70.jpg)
![image](https://cloud.githubusercontent.com/assets/1382976/10454714/0ce20b6e-71b7-11e5-8121-7c8ac6c7da45.jpg)

**Comment by feliciaan** [comment]
Version 2.0 is released with an iPad compatible layout.
