### ISSUE TITLE
Associations API

### ISSUE THREAD

**Issue by feliciaan** [ZeusWPI/hydra#215]
@mlumingu: we would like to have an associations api, which would preferably be an auto-updated json.
A possible format would be: https://github.com/ZeusWPI/hydra/blob/master/iOS/Resources/Associations.json, this json is created from the csv database dump with this script: https://github.com/ZeusWPI/hydra/blob/master/scripts/parse_associations.py.

Another feature we would like to have is an API for the associations logos or shields. This would be used in the event view, for when no Facebook event is coupled.

**Comment by mlumingu** [comment]
ah yes, the first issue I already have on my to do list :). I will try to fix both things this semester.

**Comment by feliciaan** [comment]
Created by @mlumingu on http://student.ugent.be/hydra/api/1.0/associations.json
