### ISSUE TITLE
Create folder with logos of all associations

### ISSUE THREAD

**Issue by feliciaan** [ZeusWPI/hydra#219]
Currently there is no centralised location where the logos of all associations can be found.
In hydra we could use these logos to create a better interface when an event doesn't have a linked photo.

So the task is to create a folder with all the logos as PNGs with a format of 120x120px, and name `internalName.png`.

The `internalName` <=> association mapping can be found [here](http://student.ugent.be/hydra/api/1.0/associations.json).

Other useful links are [durfdoen.be](http://durfdoen.be) for logos of most student associations and the [shields folder in fk-enrolment](https://github.com/ZeusWPI/FK-enrolment/tree/master/app/assets/images/shields) for associations from FK.

**Comment by nielsdg** [comment]
Can't we just ask from the DSA to put it in their API as well?

**Comment by feliciaan** [comment]
The goal is to host it on the DSA servers :) but they currently do not have logos.

**Comment by niknetniko** [comment]
Done
