### ISSUE TITLE
Resto API - V2.0

### ISSUE THREAD

**Issue by nielsdg** [ZeusWPI/hydra#220]
The meta-issue for everything about the 2.0 version for our API
- [x] Add Sint-Jansvest (issue #150)
- [x] Support both English and Dutch
- [x] Add sandwiches (maybe even in 1.0?)
- [x] Add opening hours for the resto's
- [x] Differentiate between veggie, meat and soup meals
- [x] Support for the different pricing in some resto's (issue #202)

**Comment by bmesuere** [comment]
Did you talk to DICT or afdeling maaltijdvoorzieningen about this?

**Comment by nielsdg** [comment]
I thought @feliciaan had already organised some meetings with them in the past, but apparently I was mistaken. Will do then!

**Comment by bmesuere** [comment]
Since they now use TVs to display the menu information, they probably use something similar or could benefit from such implementation.

**Comment by axd1967** [comment]
I have talked to them. They generate images as the end of a rather tedious manual process.

**Comment by axd1967** [comment]
FYI, I asked DICT if following can be used, but got no answer yet, I'll put it here anyway:
(are you aware of)
* list of weeks: http://www.ugent.be/student/nl/meer-dan-studeren/resto/weekmenu/overzicht/@@rss2json
* day menus: http://www.ugent.be/student/nl/meer-dan-studeren/resto/weekmenu/week04/@@rss2json

**Comment by fiterbek** [comment]
I can confirm you can use these rss2json feeds. Does the Hydra app currently scrape the resto pages for this information? In that case, the above feeds will most certainly be more efficient for Hydra as well as for the load on the UGent portal site. 

Furthermore, the URL for Sint-Jansvest is: http://www.ugent.be/student/nl/meer-dan-studeren/resto/weekmenu-sintjansvest/week03/@@rss2json

Please note that it is the responsible editor for the resto pages who decides if a week is shown with or without the zero (week03 vs week3), as all these pages are created manually. This is a nuisance, but easily caught with some code. 
We currently do the same for the m.ugent.be site.

**Comment by feliciaan** [comment]
In @ZeusWPI/hydra-iOS#2 we're having a problem with parsing of week 10. We thought using the json, but this one also doesn't contain week10. 

Mentioning @nielsdg

**Comment by feliciaan** [comment]
Weeks:
```Weekmenu 1 tot 5 februari
http://www.ugent.be/student/nl/meer-dan-studeren/resto/weekmenu/week05
Weekmenu 29 februari tot 4 maart
http://www.ugent.be/student/nl/meer-dan-studeren/resto/weekmenu/week09
Weekmenu 07 tot 11 maart
http://www.ugent.be/student/nl/meer-dan-studeren/resto/weekmenu/week11
Weekmenu 14 tot 18 maart
http://www.ugent.be/student/nl/meer-dan-studeren/resto/weekmenu/week12
Weekmenu 21 tot 25 maart
http://www.ugent.be/student/nl/meer-dan-studeren/resto/weekmenu/week13
Weekmenu 28 maart tot 01 april
http://www.ugent.be/student/nl/meer-dan-studeren/resto/weekmenu/week14```

**Comment by feliciaan** [comment]
Pull request #232 contains also fixes for this.
