### ISSUE TITLE
 toon alle verenigingen knop werkt fout

### ISSUE THREAD

**Issue by JensTimmerman** [ZeusWPI/hydra#223]
Als ik  toon alle verenigingen op 'on' zet zie ik geen verenigingen meer in het home scherm, ipv allemaal.

als ik hem op off zet kan ik verenigingen kiezen die ik wil zien.

Dit is gewoon fout?

**Comment by feliciaan** [comment]
Die knop wordt gebruikt voor twee gevallen, namelijk de feed waar enkel verenigingen tonen als er aparte geselecteerd zijn, en de aparte verenigingen view die alle activiteiten toont.

**Comment by JensTimmerman** [comment]
maar bij het ene geval betekend on on, en in het nadere betekend on off, da's wel wat verwarrend?

**Comment by feliciaan** [comment]
Ja, daarom dat de issue niet gesloten is :(
