### ISSUE TITLE
Resto API calendar numbering issue

### ISSUE THREAD

**Issue by feliciaan** [ZeusWPI/hydra#225]
The numbering of weeks are not using the same standar.
iOS uses the gregorian calendar week numbering, the API and android use the ISO 8601 week numbering.

Proposed fix: add both weeks to the same week file.

**Comment by Silox** [comment]
I wouldn't close this. The current fix works but is quite an ugly hack and we should find a better solution to deal with this in the future.

Possible solutions:
- Enforce both apps to use the same calender standard
- Change from week-based json files to day-based json files (but this would result in more calls to the API)

(Refering #220 as this should be part of the new API version)
