### ISSUE TITLE
Does not refresh menu... 

### ISSUE THREAD

**Issue by kianilannoye** [ZeusWPI/hydra#230]
Menu is not updated for over two weeks

**Comment by NoctuaNivalis** [comment]
Could you provide a bit more details? Which menu, for instance? As far as we know, the resto-menu updated fine. The activities may not have changed, but that's probably because there are hardly any activities this time of the year.

**Comment by Silox** [comment]
Seems to work fine on my phone. Can you try clearing the cache of the application and see if the problem persists?

**Comment by kianilannoye** [comment]
The daily menu (providing the information about the food)  is empty

**Comment by Silox** [comment]
So have you cleared your cache and was it empty afterwards, or was it empty beforehand and clearing your cache didn't help?

**Comment by kianilannoye** [comment]
Clearing the cache didn't help. Reinstalling the app didn't help either. https://www.dropbox.com/s/k3hofus2hmj8iy8/Screenshot_2016-02-09-10-11-44.png?dl=0

**Comment by feliciaan** [comment]
@kianilannoye can you see which type of calendar you are using? Gregorian or ISO-8601?

**Comment by NoctuaNivalis** [comment]
OK, now that you've taken that screenshot, we can start. Now, we know
- You're reporting a bug for the Android app;
- Which menu is broken.

**Comment by feliciaan** [comment]
Did it work in January?

**Comment by NoctuaNivalis** [comment]
@kianilannoye if you could answer @feliciaan's question, we'd probably be able to determine the problem, but it's not that easy to find out the answer. We're looking for an easy way to find it, reporting back in a minute.

**Comment by kianilannoye** [comment]
I can't confirm with a 100% certainty,  but I don't think it was working in January

**Comment by feliciaan** [comment]
The problem is that it uses Gregorian week numbering instead of ISO 8601, this an OS setting, that should have been override in the code :(. A possible solution is to use pull request #226 which is somewhat of a hack.
