### ISSUE TITLE
Sailfish OS / Ubuntu Touch

### ISSUE THREAD

**Issue by d9h20f** [ZeusWPI/hydra#243]
Indien iemand zich geroepen voelt en tijd heeft zou een versie van Hydra voor [Sailfish](https://sailfishos.org/wiki/Application_Development) en/of Ubuntu zeer welkom zijn. Pure GNU/Linux, wat wil een mens nog meer?

**Comment by feliciaan** [comment]
This would be a totally new codebase, but @d9h02f feel free to develop it 👍

**Comment by niknetniko** [comment]
This is out of scope for now, but if anyone does want to work on this, feel free to re-open the issue.
