### ISSUE TITLE
Change studentenmobiliteit to fietsambassade

### ISSUE THREAD

**Issue by niknetniko** [ZeusWPI/hydra#250]
Studentenmobiliteit has rebranded to 'De Fietsambassade', in the information/usefull links section we still use 'studentenmobiliteit'

Copied from ZeusWPI/hydra-android#190.

Relevant file(s): https://github.com/ZeusWPI/hydra/tree/master/scraper/info

**Comment by feliciaan** [comment]
All info pages should be updated to the new academic years

**Comment by niknetniko** [comment]
Fixed in #256.
