### ISSUE TITLE
Define meal kinds in resto scraper

### ISSUE THREAD

**Issue by feliciaan** [ZeusWPI/hydra#262]
Currently we have the following meal kinds: `meat`, `fish`, `vegetarian`. 
I propose we also add a `vegan` type, and enforce the scraper to emit one of the correct kinds.

**Comment by niknetniko** [comment]
I propose we also add an `unkown` or `general` kind for any future kinds that we don't yet support. That way, we can add a generic food icon or reuse one from the other kinds in the app, depending on what we want
