### ISSUE TITLE
Process results of user study

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/hydra#274]
[IME final report Chimaera.pdf](https://github.com/ZeusWPI/hydra/files/2266994/IME.final.report.Chimaera.pdf)

**Comment by niknetniko** [comment]
While an interesting read, I don't think there is anything actionable at the moment:

- We won't add mails
- Ufora has its own app, and I don't think Zeus has the bandwidth (or is interested in) re-implementing it in Hydra.
