### ISSUE TITLE
Move assistant to its own repo

### ISSUE THREAD

**Issue by niknetniko** [ZeusWPI/hydra#287]
The backend for assistants (only Google for now) should move to it's own repo somewhere. The goal is to only have API/website related stuff here (the resources can stay since they don't change a lot).

This is necessary, since Travis does a full deploy every time master changes, even if nothing relevant has happened.

**Comment by niknetniko** [comment]
Implemented.

**Comment by wschella** [comment]
What repo is it in?

**Comment by niknetniko** [comment]
https://github.com/ZeusWPI/hydra-assistant

Op do 5 sep. 2019 19:40 schreef Wout Schellaert <notifications@github.com>:

**Comment by wschella** [comment]
How did i not find that :man_facepalming:
