### ISSUE TITLE
Host UGent news ourselves

### ISSUE THREAD

**Issue by niknetniko** [ZeusWPI/hydra#292]
As part of https://github.com/ZeusWPI/hydra/issues/246, the DSA replaced the old news with the general UGent news feed.

Apart from historical reasons, I don't think there are any reasons why DSA should be hosting the news or why we can't do it ourselves as part of the cronjobs (the current implementation just reads the rss to json).

**Comment by niknetniko** [comment]
(also not really anything to do with recent issues with the feed, just made me think of it)

**Comment by niknetniko** [comment]
Consensus is that we should do this.

**Comment by niknetniko** [comment]
The UGent sites provides following url: https://www.ugent.be/nl/actueel/overzicht/@@rss2json. We can:
- Do nothing and use this URL directly (easiest, but more dependency on UGent, but realistically, we are always dependant, no matter the solution)
- Use some kind of redirect from our own url to this url
- Copy the contents from the url regularly and serve it from our own servers

**Comment by wschella** [comment]
I prefer the redirect method. We don't want an actual HTTP redirect, but we can forward the request (and cache it) on our servers. That enables us to monkey patch some error codes in for example.

**Comment by niknetniko** [comment]
Android now uses the UGent API directly. This also enables us to show English news. Hosting it ourselves isn't worth the effort at the moment, as I believe the UGent API to be relatively stable. If we see that it breaks every week, we can revisit this.
