### ISSUE TITLE
Support uurrooster

### ISSUE THREAD

**Issue by Frederik-Baetens** [ZeusWPI/hydra#307]
Zijn jullie van plan om opnieuw het uurrooster in de app te ondersteunen?

**Comment by niknetniko** [comment]
Op dit moment zijn daar geen concrete plannen voor, aangezien Ufora zelf een eigen app heeft en die app ondersteuning heeft voor het lessenrooster. Het lijkt ons niet zo nuttig om die functionaliteit dubbel aan te bieden.

**Comment by Frederik-Baetens** [comment]
Is dat een echte androidapp of gewoon een webapp? Ik vind de app op het eerste zicht niet in de play store.

**Comment by niknetniko** [comment]
Het gaat om deze app: https://play.google.com/store/apps/details?id=com.d2l.brightspace.student.android&hl=nl

Brightspace is de naam van het systeem waarvan Ufora gebruik maakt. Voor meer informatie (ook voor bv. iOS) verwijs ik graag naar onze helppagina: https://hydra.ugent.be/help/minerva.html, waar hopelijk de meeste vragen beantwoord zijn.

**Comment by niknetniko** [comment]
Ik wou ook nog even melden dat de UGent misschien volgend jaar de lessenroosters overbrengt naar Office365, maar dat moet bekeken worden als het zo ver is.
