### ISSUE TITLE
Run scraper twice a day

### ISSUE THREAD

**Issue by niknetniko** [ZeusWPI/hydra#337]
Also run it in the evening, around 8 PM or so. E.g. the menu for the next week is often only available after Sunday noon.

**Comment by redfast00** [comment]
willdo!

**Comment by niknetniko** [comment]
FYI, the cron schedule is set by this code: https://github.com/ZeusWPI/hydra/blob/13deaa04bb1262cda09827510a79a5139efeac7f/server/deploy_remote_ii.sh#L62-L70

**Comment by redfast00** [comment]
Is there something I'm missing? To me it seems like you can just copy and edit the resto 10 am line, no?

**Comment by niknetniko** [comment]
> Is there something I'm missing?

No

>  To me it seems like you can just copy and edit the resto 10 am line, no?

Yes, this conversation probably required more time than the time needed to actually do the change, but I'm lazy. 😐

**Comment by redfast00** [comment]
Done!
