### ISSUE TITLE
Add more information to resto/meta.json

### ISSUE THREAD

**Issue by javache** [ZeusWPI/hydra#42]
See list at http://www.ugent.be/nl/voorzieningen/resto/studenten/waar.htm. Openinghours etc would be useful.
It would probably be good to store a type with each record as well ('resto' or 'cafetaria') to distinguish them.

**Comment by nielsdg** [comment]
the selection of sandwiches could be a nice addition as well?

**Comment by feliciaan** [comment]
@nielsdg added sandwiches, for new items we should create new issues.
