### ISSUE TITLE
https://dsa.ugent.be/api/spec is not accessible

### ISSUE THREAD

**Issue by mattis1231231** [ZeusWPI/hydra#474]
I get an "Internal Server Error" when I access the website.

**Comment by redfast00** [comment]
This might be on https://dsa.ugent.be/swagger instead (but note that DSA and Zeus are separate entities)

**Comment by redfast00** [comment]
Well, I'm not either anymore, so can't really tell you that. What do you want to use the API for?

**Comment by mattis1231231** [comment]
In the Hydra app on the home screen you have the activities of all student associations, basically the same use case.

**Comment by redfast00** [comment]
Sounds good, you might get the API docs by sending an email to [dsa@ugent.be](mailto:dsa@ugent.be)
