### ISSUE TITLE
Implement Crashlytics

### ISSUE THREAD

**Issue by javache** [ZeusWPI/hydra#88]

**Comment by Silox** [comment]
Why not errbit, where all errors from other apps are already gathered?

**Comment by feliciaan** [comment]
1. Crashlytics SDK is more advanced, and more tested than the errbit sdk. (Errbit sdk is 2 years old)
2. We will get errors, even as or servers are down, or a configuration mistake makes it impossible to reach the server.
3. More advanced interface, and support for symbols. So it's easier to directly find the bug. You also get more info about the device that has the bugs.

**Comment by feliciaan** [comment]
It's now build into iOS.
